# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRT', '0003_auto_20160822_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='director',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
